const MAX_FILES = 6, MAX_FILE_SIZE_BYTES = 10 * 1024 * 1024;
const allowedTypes = new Set(["image/jpeg", "image/png"]);
const apiUrl = window.PHOTO_UPLOAD_FUNCTION_URL;
const params = new URLSearchParams(window.location.search), session = params.get("session"), token = params.get("token");
const input = document.querySelector("#photos"), filesList = document.querySelector("#files"), sendButton = document.querySelector("#send"), status = document.querySelector("#status"), sessionError = document.querySelector("#session-error");
function setStatus(message, type = "") { status.textContent = message; status.className = `notice ${type}`; }
function selectedFiles() { return Array.from(input.files ?? []); }
function validate(files) { if (!session || !token) return "O link do QR está incompleto. Gere outro QR no computador."; if (!apiUrl) return "O endereço seguro de upload ainda não foi configurado."; if (files.length < 1 || files.length > MAX_FILES) return "Escolha entre uma e seis fotos."; return files.some((file) => !allowedTypes.has(file.type) || file.size > MAX_FILE_SIZE_BYTES) ? "Use somente JPEG ou PNG de até 10 MB por foto." : null; }
function renderFiles() { const files = selectedFiles(); filesList.replaceChildren(...files.map((file) => { const item = document.createElement("li"); item.textContent = `${file.name} (${Math.ceil(file.size / 1024)} KB)`; return item; })); const error = validate(files); sendButton.disabled = Boolean(error); setStatus(error ?? `${files.length} foto(s) pronta(s) para envio.`, error ? "error" : ""); }
async function api(body) { const response = await fetch(apiUrl, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ session, token, ...body }) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error ?? "Não foi possível enviar as fotos."); return data; }
async function upload() { const files = selectedFiles(), error = validate(files); if (error) return setStatus(error, "error"); try { input.disabled = true; sendButton.disabled = true; setStatus("Preparando envio seguro…"); const metadata = files.map((file) => ({ filename: file.name, mimeType: file.type, size: file.size })); const { uploads } = await api({ action: "prepare", files: metadata }); for (let index = 0; index < files.length; index += 1) { setStatus(`Enviando foto ${index + 1} de ${files.length}…`); const response = await fetch(uploads[index].signedUrl, { method: "PUT", headers: { "Content-Type": files[index].type, "x-upsert": "false" }, body: files[index] }); if (!response.ok) throw new Error(`A foto ${index + 1} não pôde ser enviada.`); metadata[index].storagePath = uploads[index].storagePath; } const result = await api({ action: "complete", files: metadata }); input.value = ""; renderFiles(); setStatus(`${result.accepted} foto(s) recebida(s). Você pode fechar esta página.`, "success"); } catch (uploadError) { setStatus(uploadError instanceof Error ? uploadError.message : "Falha ao enviar as fotos.", "error"); } finally { input.disabled = false; sendButton.disabled = selectedFiles().length === 0; } }
if (!session || !token) { sessionError.textContent = "Este QR não contém uma sessão válida. Volte ao AutoOS e gere outro QR."; sessionError.hidden = false; }
input.addEventListener("change", renderFiles); sendButton.addEventListener("click", upload);
